# Project information
site_name: 'AutoConnect for ESP8266/ESP32'
site_description: 'ESP8266/ESP32 WLAN configuration at run time with web interface'
site_author: 'Hieromon Ikasamo'
site_url: 'https://Hieromon.github.io/AutoConnect/'

# Docs
docs_dir: 'mkdocs'

# Pages
nav:
  - 'Overview' : index.md
  - 'Getting started' : gettingstarted.md
  - 'AutoConnect menu' : menu.md
  - 'Basic usage' : basicusage.md
  - 'Advanced usage' :
    - 'Advanced usage' : advancedusage.md
    - 'AutoConnect WiFi connection control' : adconnection.md
    - 'Captive portal control' : adcpcontrol.md
    - 'Settings and controls for network and WiFi' : adnetwork.md
    - 'Authentication settings' : adauthentication.md
    - 'Credential accesses' : adcredential.md
    - 'Customizing page appearance' : adexterior.md
    - 'Other operation settings and controls' : adothers.md
  - 'Custom Web pages' :
    - 'Custom Web pages with AutoConnect' : acintro.md
    - 'AutoConnectElements' : acelements.md
    - 'Custom Web pages with JSON' : acjson.md
    - 'Handling the custom Web pages' : achandling.md
  - 'OTA Updates' : 
    - 'OTA Updates' : otaupdate.md
    - 'Using Web Browser' : otabrowser.md
    - 'Using Update Server' : otaserver.md
  - 'Using Filesystem' : filesystem.md
  - 'Library APIs' :
    - 'AutoConnect API': api.md
    - 'AutoConnectAux API': apiaux.md
    - 'AutoConnectConfig API': apiconfig.md
    - 'AutoConnectElements API': apielements.md
    - 'AutoConnectUpdate API' : apiupdate.md
    - 'Something extra': apiextra.md
  - 'Examples' :
    - 'How to embed': howtoembed.md
    - 'Tips for data conversion': datatips.md
    - 'Attach the menus': menuize.md
    - 'Custom Web pages w/o JSON': wojson.md
    - 'Works with ESP32-CAM': esp32cam.md
  - 'Appendix':
    - 'Inside AutoConnect::begin': lsbegin.md
    - 'Saved credentials access': credit.md
    - 'File upload handler': acupload.md
    - 'Custom colorized': colorized.md
    - 'Change label text': changelabel.md
  - 'FAQ' : faq.md
  - 'Change log' : changelog.md
  - 'License' : license.md

# Repository
repo_name: Hieromon/AutoConnect
repo_url: https://github.com/Hieromon/AutoConnect
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2018-2021 Hieromon Ikasamo

# Configuration
use_directory_urls: false
theme:
  name: material
  language: en
  logo: images/arduino-logo.svg
  icon:
    logo: logo
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

# Customization
extra_css:
  - css/paragraph.css
  - css/extra.css
  - https://use.fontawesome.com/releases/v5.6.3/css/all.css
extra_javascript:
  - js/gifffer.min.js
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Hieromon
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/hieromon
  analytics:
    provider: google
    property: !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.highlight:
      guess_lang: false
      linenums: none
      use_pygments: true
      noclasses: true
      pygments_style: monokai
  - footnotes
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: Hieromon
      repo: AutoConnect
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - toc:
      permalink: true
